"""
Authentication
"""

USER_COOKIE = ""
DISCORD_TOKEN = ""  ## hahaha get token logged!! no111!!! its for the valuealgo thing that generates custom values


"""
Trade Settings
"""

MIN_TRADE_ATTRACTIVENESS = -0.2
MAX_TRADE_ATTRACTIVENESS = 0.3

DO_NOT_TRADE_FOR = []
DO_NOT_TRADE_AWAY = [1365767, 439946101, 4255053867, 6550129, 182509980]


MIN_ITEM_VOLUME = 0  # add la
# TRADE_BIGS_OR_SMALLS = "mixed"  # sort lol

# Min/max values for trades
MIN_RAP_WIN = -1000
MAX_RAP_WIN = 2000
MIN_VALUE_WIN = 1
MAX_VALUE_WIN = 2000
# CHECK_INBOUND_TRADES = False

# Min/max values for items
MIN_ITEM_RAP = 0
MAX_ITEM_RAP = 9999999
MIN_ITEM_VALUE = 0
MAX_ITEM_VALUE = 99999999

# Other
MIN_ITEM_AGE = 1000
SEND_MIXED_TRADES = True
LAST_ONLINE = 600000  # 24 hours
MAX_ITEM_HOARD = 2

"""
Advanced
"""
IP_LOCK_BYPASS = True
USER_WEBHOOK = ""
ROLIMON_AD_SNIPE = True
CUSTOM_TRADE_RATIOS = {}
CUSTOM_VALUE_RATIOS = {}
DELETE_TRADE_MESSAGES = True
MAX_TIME_FOR_TRADES = 14
ADJUST_TRADE_COOLDOWN = True
